package MtM.view.swingcomponents;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.JLayeredPane;
import javax.swing.border.Border;

/**
 *
 * @author Colin
 */
public class MButton extends JLayeredPane implements MouseListener {

    protected int btnID;
    protected boolean selected, active;
    protected static Border borderHover, borderDefault;
    protected MPanel mPanel;
    
    private static final Color COLOR_ACTIVE_SELECTED = new Color(200, 50, 250);
    private static final Color COLOR_INACTIVE_SELECTED = Color.red;
    private static final Color COLOR_ACTIVE_UNSELECTED = new Color(100, 0, 200);
    private static final Color COLOR_INACTIVE_UNSELECTED = Color.gray;

    /**
     * Creates new form MinionButton
     *
     */
    public MButton() {
        initComponents();
        this.btnID = 0;
        this.addMouseListener(this);
        borderHover = BorderFactory.createLineBorder(Color.green);
        borderDefault = BorderFactory.createLineBorder(Color.black);
        this.setBorder(borderDefault);
        selected = false;
        active = false;
        this.dispatchEvent(new ActionEvent(this, ActionEvent.ACTION_FIRST, "paint"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(10000, 100000));
        setMinimumSize(new java.awt.Dimension(50, 50));
        setOpaque(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mousePressed(MouseEvent e) {
        processPress();

    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        this.requestFocus();
        this.setBorder(borderHover);
    }

    @Override
    public void mouseExited(MouseEvent e) {
        this.setBorder(borderDefault);
    }

    protected void updateColor() {
        if (selected) {
            if (active) {
                this.setBackground(COLOR_ACTIVE_SELECTED);
            } else {
                this.setBackground(COLOR_INACTIVE_SELECTED);
            }
        } else {
            if (active) {
                this.setBackground(COLOR_ACTIVE_UNSELECTED);
            } else {
                this.setBackground(COLOR_INACTIVE_UNSELECTED);
            }
        }
    }

    public int getBtnID() {
        return btnID;
    }

    public void setBtnID(int btnID) {
        this.btnID = btnID;
    }

    public MPanel getmPanel() {
        return mPanel;
    }

    public void setMPanel(MPanel mPanel) {
        this.mPanel = mPanel;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        updateColor();
    }

    public void processPress() {
        setSelected(true);
        mPanel.processSelection(btnID);
    }

    public void setActive(boolean state) {
        active = state;
        updateColor();
    }

    public boolean getActive() {
        return active;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
