/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MtM.view.swingcomponents;

import java.awt.Graphics;
import javax.swing.JScrollPane;

/**
 *
 * @author Colin
 */
public class MinionPane extends JScrollPane {

    private MinionButton[] btnArray;
    private int index, selected;

    /**
     * Creates new form MinionPane
     */
    public MinionPane() {
        initComponents();
        btnArray = new MinionButton[5];
        index = 0;
        setViewportView(viewPanel);
        viewPanel.setLayout(null);
    }

    public void addMinionBtn() {
        MinionButton newBtn = new MinionButton();
        int size = viewPanel.getWidth() - 20;
        newBtn.setSize(size, size);
        newBtn.setLocation(10, 10 + index * (size + 10));
        newBtn.setBtnID(index);
        btnArray[index] = newBtn;
        index++;
        viewPanel.add(newBtn);
        newBtn.setMinionPane(this);
        newBtn.processPress();
    }
    
    public void processSelection(int id) {
        selected = id;
        for (int i = 0; i < index; i++) {
            if(btnArray[i] == null || i == selected) continue;
            btnArray[i].setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();

        setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(60, 400));
        setViewportView(viewPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
