package MtM.view.swingcomponents;

import java.awt.Dimension;

/**
 *
 * @author Colin
 */
public class MinionPanel extends MPanel {
    public MinionPanel() {
        super();
    }

    public void addMinionBtn(String name) {
        MinionButton newBtn = new MinionButton();
        int size = getWidth();
        newBtn.setPreferredSize(new Dimension(size - 10, size / 2 - 20));
        newBtn.setBtnID(index);
        newBtn.setMinionName(name);
        btnArray[index++] = newBtn;
        add(newBtn);
        newBtn.setMPanel(this);
        newBtn.processPress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

    public int getNumMinions() {
        return index;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
