package MtM.view.swingcomponents;

/**
 *
 * @author Colin
 */
public class MissionButton extends MButton {

    /**
     * Creates new form MissionButton
     */
    public MissionButton() {
        super();
        initComponents();
        
        availableLabel.setBounds(progressBar.getBounds());
    }

    public void setAvailable() {
        moveToFront(availableLabel);
        moveToBack(progressBar);
    }

    public void setDone() {

    }

    public void setActive() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeLabel = new javax.swing.JLabel();
        availableLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        doneLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(10000, 10000));
        setPreferredSize(new java.awt.Dimension(80, 70));

        typeLabel.setFont(typeLabel.getFont().deriveFont(typeLabel.getFont().getSize()+11f));
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Type");
        typeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        typeLabel.setMaximumSize(new java.awt.Dimension(80, 40));
        typeLabel.setMinimumSize(new java.awt.Dimension(80, 40));
        typeLabel.setPreferredSize(new java.awt.Dimension(80, 40));

        availableLabel.setFont(availableLabel.getFont().deriveFont((availableLabel.getFont().getStyle() | java.awt.Font.ITALIC), availableLabel.getFont().getSize()+6));
        availableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        availableLabel.setText("Available");
        availableLabel.setPreferredSize(new java.awt.Dimension(80, 40));

        progressBar.setToolTipText("");
        progressBar.setMaximumSize(new java.awt.Dimension(80, 40));
        progressBar.setMinimumSize(new java.awt.Dimension(80, 40));
        progressBar.setOpaque(true);
        progressBar.setPreferredSize(new java.awt.Dimension(80, 40));

        doneLabel.setFont(doneLabel.getFont().deriveFont((doneLabel.getFont().getStyle() | java.awt.Font.ITALIC), doneLabel.getFont().getSize()+6));
        doneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doneLabel.setText("DONE");
        doneLabel.setMaximumSize(new java.awt.Dimension(80, 20));
        doneLabel.setMinimumSize(new java.awt.Dimension(80, 20));
        doneLabel.setPreferredSize(new java.awt.Dimension(80, 20));

        setLayer(typeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(availableLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(progressBar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(doneLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(availableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableLabel;
    private javax.swing.JLabel doneLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    void setMissionType(String type) {
        typeLabel.setText(type);
    }

}
